services:
  mysql:
    image: 'mysql:8.1.0'
    container_name: 'listcontainer'
    environment:
      - 'MYSQL_DATABASE=listdb'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
