apiVersion: apps/v1
kind: Deployment
metadata:
  name: list
  labels:
    app: list
spec:
  replicas: 1
  selector:
    matchLabels:
      app: list
  template:
    metadata:
      labels:
        app: list
    spec:
      containers:
      - name: list
        image: localhost:32000/{{IMAGE}}:{{VERSION}}.{{BUILD_NUMBER}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          failureThreshold: 30
          periodSeconds: 2
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          periodSeconds: 10
        env:
        - name: "SPRING_PROFILES_ACTIVE"
          value: "prod"
